<a href="https://colab.research.google.com/github/couqdev/MachineLearning/blob/main/Lab_1_20130376_TranDangQuoc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [74]:
# Task 1.1
print("Nhap n: ")
n = int(input())
data = []
for i in range(n):
  data.append(int(input("x("+str(i)+") = ")))
print("Max: ")
print(max(data))
print("Min: ")
print(min(data))
print("Sum: ")
print(sum(data))
print("Sorted: ")
print(sorted(data))

a = 0
d = 0
for j in data:
  if j< 0:
    a = a+1
  elif(j>0):
    d = d+1
print("So am: ")
print(a)
print("So duong: ")
print(d)


Nhap n: 
4
x(0) = -2
x(1) = 9
x(2) = 4
x(3) = 5
Max: 
9
Min: 
-2
Sum: 
16
Sorted: 
[-2, 4, 5, 9]
So am: 
1
So duong: 
3


In [75]:
# Task 1.2
def Sn(n):
  sn = 0
  for i in range(n +1):
    sn += 1/(2*i+1)
  return sn

print(Sn(1))


1.3333333333333333


In [132]:
# Task 1.3
import datetime as d
class Product(object):
  def __init__(self, name, kind, price, expiredDate):
    self.name = name
    self.kind = kind
    self.price = price
    self.__expiredDate =expiredDate

  def toString(seft):
    return seft.name

  def getPrice(seft):
    return seft.price
  
  def getName(seft):
    return seft.name
  def getKind(seft):
    return seft.kind

class OderItem(object):
  def __init__(self, item, amount):
    self.item = item
    self.amount = amount

  def getItem(seft):
    return seft.item

  def getAmount(seft):
    return seft.amount

class Order(object):
  def __init__(self, id, customer, employee, date):
    self.__id =id
    self.__customer =customer
    self.__employee = employee
    self.__date = date
    self.items = list()

  def addItems(seft, orderItems):
    return seft.items.append(orderItems)

class OrderManager():
  def __init__(seft):
    seft.orders = list()
  
  def addOrder(seft, order):
    return seft.orders.append(order)

  def getOrders(seft):
    return seft.orders

  def highestPrice(seft):
    max = 0
    name = ""
    for i in seft.orders:
      for j in i.items:
        if(max < j.getItem().getPrice()):
          max = j.getItem().getPrice()
          name = j.getItem().getName()

      return name
  def quantityStatistics(seft):

    kind = {}
    for i in seft.orders:
      for j in i.items:
        if j.getItem().getKind() in kind:
          kind[j.getItem().getKind()] = kind[j.getItem().getKind()] + j.getAmount()
        elif j.getItem().getKind() not in kind:
          kind[j.getItem().getKind()] = j.getAmount()
            
    return kind

if __name__ == "__main__":
   product1 = Product("Yamaha R1","Motocycle",10000,d.date(2015,7,10))
   product2 = Product("Kawasaki ZX-10R","Motocycle",28313232,d.date(2015,6,10))
   product3 = Product("Ducati V4s","Motocycle",821172,d.date(2018,1,18))
   product4 = Product("Bmw M2","Car",92022,d.date(2019,1,18))
   product5 = Product("Honda Cbr1000RRR","Motocycle",947372,d.date(2019,1,16))
   product6 = Product("Suzuki GSX1000R","Motocycle",1929873,d.date(2015,7,18))
   
   oderItem1 = OderItem(product1,7)
   oderItem2 = OderItem(product2,2)
   oderItem3 = OderItem(product3,6)
   oderItem4 = OderItem(product4,7)
   oderItem5 = OderItem(product5,9)
   oderItem6 = OderItem(product6,10)

   order1 = Order("#1","Tran", "Nhan vien", d.date(2023,2,20))
   order1.addItems(oderItem1)
   order1.addItems(oderItem2)
   order1.addItems(oderItem5)
   order1.addItems(oderItem6)
   order2 = Order("#2","Dang", "Truong phong", d.date(2023,2,20))
   order2.addItems(oderItem1)
   order2.addItems(oderItem2)
   order2.addItems(oderItem4)
   order3 = Order("#3","Quoc", "Bao ve", d.date(2023,2,20))
   order3.addItems(oderItem1)
   order3.addItems(oderItem3)

   orderManager = OrderManager()
   orderManager.addOrder(order1)
   orderManager.addOrder(order2)
   orderManager.addOrder(order3)
   
   print("San pham co gia cao nhat: ")
   print(orderManager.highestPrice())
   print("Thong ke so luong san pham theo loai: ")
   print(orderManager.quantityStatistics())

San pham co gia cao nhat: 
Kawasaki ZX-10R
Thong ke so luong san pham theo loai: 
{'Motocycle': 50, 'Car': 7}


In [131]:
import numpy as np
# Task 2.1
arr1  = np.arange(10,26,1)
print(arr1)
temporary = 0
stop = arr1.size/2
size = arr1.size
len =0
x= 0
for i in arr1:
  size = size -1
  if x<stop:
    temporary = arr1[size]
    arr1[size] = i
    arr1[x] = temporary
  x+=1
print(arr1)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]
[25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [133]:
# Task 2.2
def repeat(array, n):
  temporary = array.size*n
  data = np.arange(0,temporary,1)
  x =0
  for i in range(temporary):
    data[i] = array[x]
    x= (x+1)%4

  return data

print(repeat(np.array([1,2,3,4]), 5))

[1 2 3 4 1 2 3 4 1 2 3 4 1 2 3 4 1 2 3 4]


In [78]:
# Task 2.3
def thanDotFive(array2d):
  x = 0
  y = 0
  a = -1
  b = -1
  for i in array2d:
    a +=1
    for j in i:
      b +=1
      x = (int)(j)
      y = j -x
      if y>0.5:
        array2d[a,b] = x + 0.5
    b = -1
  return array2d

print("Input: ")
print(np.array([[ 0.42, 0.48, 0.32],[ 0.74, 0.58, 0.38],[ 0.51, 0.34, 0.15 ]]))
print("Output: ")
print(thanDotFive(np.array([[ 0.42, 0.48, 0.32],[ 0.74, 0.58, 0.38],[ 0.51, 0.34, 0.15 ]])))
print("---------------------------------------------")
print("Input: ")
print(np.array([[ 7.6, 3.3, 0.32],[ 0.74, 1.58, 0.38]]))
print("Output: ")
print(thanDotFive(np.array([[ 7.6, 3.3, 0.32],[ 0.74, 1.58, 0.38]])))

Input: 
[[0.42 0.48 0.32]
 [0.74 0.58 0.38]
 [0.51 0.34 0.15]]
Output: 
[[0.42 0.48 0.32]
 [0.5  0.5  0.38]
 [0.5  0.34 0.15]]
---------------------------------------------
Input: 
[[7.6  3.3  0.32]
 [0.74 1.58 0.38]]
Output: 
[[7.5  3.3  0.32]
 [0.5  1.5  0.38]]
